const scene = '<div class="scene-slot" aria-label="Interactive car preview"></div>';
const launch = '<button class="primary" data-view="training">Enter training &rarr;</button>';
const freeplay = '<button class="secondary" data-action="freeplay">Free play</button>';
const resume = '<button class="resume" data-view="drill"><small>CONTINUE SESSION</small><strong>Air Roll Sequences</strong><span>Intermediate &rarr;</span></button>';
const heading = (kicker, title) => `<div class="layout-heading"><p class="eyebrow">${kicker}</p><h1>${title}</h1></div>`;
const choice = (entry, index) => `<button class="layout-choice" data-category="${index}"><small>${String(index + 1).padStart(2, '0')} / ${entry[2]}</small><strong>${entry[0]}</strong><span>${entry[1]}</span><b aria-hidden="true">&rarr;</b></button>`;
const choices = entries => entries.map((entry, index) => choice(entry, index)).join('');
const metrics = '<div class="layout-metrics"><span><strong>10</strong>Branches</span><span><strong>32</strong>Mechanics</span><span><strong>13</strong>Drills ready</span></div>';

export function homeLayout(layout, entries) {
  const screens = {
    garage: `<div class="garage-home"><section class="garage-commands">${heading('TRAINING GARAGE', 'READY TO<br>ROLL.')}<div class="command-stack">${launch}${freeplay}<button class="secondary" data-view="settings">Loadout &amp; setup &rarr;</button></div>${resume}</section><section class="garage-floor">${scene}<div class="floor-caption"><strong>OCTANE</strong><span>Standard body / Training spec</span><button data-action="car">Rotate preview</button></div></section><section class="garage-strip">${metrics}${choice(entries[1], 1)}</section></div>`,
    map: `<div class="map-home">${heading('YOUR CAREER', 'THE ROAD<br>AHEAD.')}<div class="route-map">${scene}<div class="route-line"></div>${entries.map((entry,index)=>`<div class="checkpoint checkpoint-${index}"><span class="checkpoint-dot">${index + 1}</span>${choice(entry,index)}</div>`).join('')}</div><div class="route-footer">${resume}${freeplay}</div></div>`,
    cards: `<div class="cards-home"><div class="deck-heading">${heading('MECHANIC COLLECTION', 'BUILD YOUR HAND.')}<div>${launch}${freeplay}</div></div><div class="deck-table">${entries.slice(0,3).map((entry,index)=>`<article class="collectible"><span class="deck-rarity">${entry[2]} / ${entry[3]} mechanics</span><div class="deck-art">${index === 0 ? scene : `<strong>${index === 1 ? '180°' : 'TOUCH'}</strong>`}</div>${choice(entry,index)}<span class="deck-rarity">AIRLAB / SERIES 01</span></article>`).join('')}</div><div class="collection-footer">${metrics}${resume}</div></div>`,
    esports: `<div class="esports-home"><div class="competition-banner"><span>TRAINING SEASON 01</span><span>SOLO / OPEN PRACTICE</span></div><div class="competition-grid"><section class="competition-main">${heading('PLAYER ONE', 'NEXT UP:<br>YOUR BEST.')}<div class="competition-stage">${scene}</div><div class="competition-actions">${launch}${freeplay}</div></section><aside class="competition-sidebar"><h2>SESSION QUEUE</h2>${resume}${choice(entries[3],3)}<h2>PLAYER SNAPSHOT</h2>${metrics}</aside></div><div class="competition-ticker"><strong>TRAINING POOL</strong><span>CONTROL / RECOVERIES / AERIALS / PINCHES</span></div></div>`,
    concourse: `<div class="concourse-home"><div class="terminal-heading">${heading('AIRLAB STADIUM', 'WHERE NEXT?')}<strong class="gate-sign">GATE<br>01 &rarr;</strong></div><div class="terminal-body"><section class="departures"><div class="departures-title"><span>DESTINATION</span><span>LEVEL</span><span>GATE</span></div>${entries.map((entry,index)=>`<button data-category="${index}"><strong>${entry[0]}</strong><span>${entry[2]}</span><b>${String(index+1).padStart(2,'0')} &rarr;</b></button>`).join('')}</section><aside class="terminal-platform">${scene}<div>${freeplay}<button class="secondary" data-view="settings">Facilities / Setup &rarr;</button></div></aside></div></div>`,
    orbit: `<div class="orbit-home"><div class="orbit-title">${heading('AIRLAB / ZERO GRAVITY', 'Find your orbit.')}</div><div class="orbital-menu">${scene}<button class="orbit-command orbit-north" data-view="training"><small>01</small><strong>Training</strong><span>Choose a mechanic</span></button><button class="orbit-command orbit-east" data-action="freeplay"><small>02</small><strong>Free play</strong><span>No limits</span></button><button class="orbit-command orbit-south" data-view="drill"><small>03</small><strong>Continue</strong><span>Air Roll Sequences</span></button><button class="orbit-command orbit-west" data-view="settings"><small>04</small><strong>Setup</strong><span>Your car. Your feel.</span></button></div></div>`,
    race: `<div class="race-home"><div class="race-masthead">${heading('PRACTICE WEEKEND / ROUND 01', 'ON THE GRID.')}<span class="race-number">01</span></div><div class="race-paddock">${scene}<div class="paddock-label"><strong>OCTANE</strong><span>READY FOR PRACTICE</span>${freeplay}</div></div><div class="race-schedule">${entries.slice(0,4).map((entry,index)=>`<section><small>SESSION ${index+1} / ${index<2?'FOUNDATION':'CONTROL'}</small>${choice(entry,index)}<span class="schedule-time">${entry[3]} MECHANICS &bull; SOLO</span></section>`).join('')}</div></div>`,
    tree: `<div class="tree-home"><aside class="tree-summary">${heading('PROGRESSION', 'ROOTED IN<br>CONTROL.')}<p>Fundamentals</p>${metrics}${resume}</aside><section class="skill-canopy"><div class="tree-root">${scene}<button class="primary" data-view="training">Car control &rarr;</button></div><div class="tree-trunk"></div><div class="tree-tier">${choice(entries[1],1)}${choice(entries[2],2)}</div><div class="tree-tier advanced-tier">${choice(entries[3],3)}${choice(entries[4],4)}${choice(entries[5],5)}</div></section></div>`,
    arcade: `<div class="arcade-home"><div class="arcade-marquee">AIRLAB <span>ARCADE</span></div><div class="arcade-screen"><div class="arcade-title">${heading('PLAYER ONE / READY', 'SELECT<br>YOUR GAME')}</div>${scene}<div class="arcade-select">${entries.slice(0,4).map(choice).join('')}</div></div><div class="arcade-console">${launch}${freeplay}<button class="secondary" data-view="settings">Options</button></div><div class="arcade-score">TRAINING POOL: 13 DRILLS <span>NO COINS REQUIRED</span></div></div>`,
    playbook: `<div class="playbook-home"><aside class="coach-notes">${heading('COACH’S DESK', 'THE NEXT<br>PLAY.')}<div class="notes-lines"><h2>Today's focus</h2>${resume}<p>01 / Orientation</p><p>02 / Controlled landing</p><p>03 / Repeat consistently</p></div>${freeplay}</aside><section class="tactical-field"><div class="field-center"></div>${scene}${entries.map((entry,index)=>`<div class="field-position field-${index}">${choice(entry,index)}</div>`).join('')}</section></div>`,
    workshop: `<div class="workshop-home"><div class="bench-toolbar"><strong>WORKSPACE / OCTANE</strong><span>CAR CONTROL LAB</span><button class="secondary" data-view="settings">Configure</button></div><div class="bench-grid"><aside class="tool-inventory"><h2>TRAINING TOOLS</h2>${choices(entries)}</aside><section class="workbench">${scene}<div class="bench-readout"><span>BODY: OCTANE</span><span>ARENA: STANDARD</span><span>BOOST: UNLIMITED</span></div></section><aside class="bench-inspector">${heading('SESSION INSPECTOR', 'READY.')}<dl><div><dt>Mechanic</dt><dd>Air Roll</dd></div><div><dt>Goals</dt><dd>4</dd></div><div><dt>Mode</dt><dd>Solo</dd></div></dl>${resume}${launch}${freeplay}</aside></div></div>`,
    championship: `<div class="championship-home"><div class="league-heading">${heading('AIRLAB CHAMPIONSHIP', 'CLIMB THE<br>DIVISIONS.')}<div class="division-seal"><strong>I</strong><span>FOUNDATION</span></div></div><div class="league-grid"><section class="division-table"><div class="table-title">DIVISION / TRAINING BRANCH</div>${entries.map((entry,index)=>`<button data-category="${index}"><b>${['I','II','III','IV','V','VI'][index]}</b><span><strong>${entry[0]}</strong><small>${entry[2]}</small></span><span>${entry[3]} mechanics &rarr;</span></button>`).join('')}</section><aside class="league-showcase">${scene}${resume}${freeplay}</aside></div></div>`,
    gallery: `<div class="gallery-home"><div class="gallery-heading">${heading('THE MECHANIC COLLECTION', 'Movement,<br>in focus.')}<div>${launch}${freeplay}</div></div><div class="gallery-feature">${scene}<div class="feature-caption"><span>001 / ORIENTATION</span><button data-view="drill"><strong>Air Roll Sequences</strong><span>Open session &rarr;</span></button></div></div><div class="gallery-reel">${entries.map(choice).join('')}</div></div>`,
    mission: `<div class="mission-home"><aside class="mission-roster">${heading('OPERATIONS', 'SELECT<br>MISSION.')}<div class="roster-list">${choices(entries)}</div></aside><section class="mission-briefing"><div class="briefing-top"><strong>OP / 001</strong><span>SOLO TRAINING</span></div>${scene}<div class="briefing-copy"><p class="eyebrow">ACTIVE BRIEFING</p><h2>Air Roll Sequences</h2><p>Orientation / Controlled timing / Consistent landings</p><div>${resume}${launch}${freeplay}</div></div></section></div>`,
    festival: `<div class="festival-home"><div class="festival-title">${heading('AIRLAB FREESTYLE CLUB', 'MAKE YOUR<br>OWN MOVES.')}${freeplay}</div><div class="poster-wall"><section class="poster poster-main"><strong>OPEN<br>SESSION</strong>${scene}${launch}</section><section class="poster poster-recovery"><span>WORKSHOP 01</span>${choice(entries[1],1)}<strong class="poster-mark">180°</strong></section><section class="poster poster-aerial"><strong class="poster-mark">AIR<br>TIME</strong>${choice(entries[3],3)}</section><section class="poster poster-reset"><span>AFTER HOURS</span>${choice(entries[5],5)}</section></div></div>`,
  };
  return screens[layout];
}

export function arrangeCatalogue(layout, content) {
  const grid = content.querySelector('.category-grid');
  if (!grid) return;
  const formats = {
    garage: ['BAY', 'bay'], map: ['CHECKPOINT', 'route'], cards: ['COLLECTION', 'deck'],
    esports: ['TRAINING POOL', 'dashboard'], concourse: ['DEPARTURES', 'board'], orbit: ['ORBITS', 'radial'],
    race: ['PRACTICE SCHEDULE', 'schedule'], tree: ['PROGRESSION BRANCHES', 'tree'], arcade: ['GAME SELECT', 'cabinet'],
    playbook: ['TACTICAL POSITIONS', 'field'], workshop: ['TOOL INVENTORY', 'inventory'], championship: ['DIVISIONS', 'table'],
    gallery: ['MECHANIC REEL', 'reel'], mission: ['MISSION ROSTER', 'roster'], festival: ['SESSION POSTERS', 'posters'],
  };
  const [label, format] = formats[layout];
  content.querySelector('.page-heading .eyebrow').textContent = label;
  grid.dataset.format = format;
  if (['board','schedule','inventory','table','roster'].includes(format)) {
    grid.querySelectorAll('.category-art').forEach(art => art.remove());
  }
  if (['route','tree','field','radial'].includes(format)) {
    const marker = document.createElement('div');
    marker.className = 'catalogue-center';
    marker.innerHTML = '<strong>AIRLAB</strong><span>CAR CONTROL</span>';
    grid.prepend(marker);
  }
}
